# Generated by Django 4.2.15 on 2024-08-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_lecturerprofile_user_alter_studentprofile_user'),
        ('project_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='supervisors',
            field=models.ManyToManyField(help_text='Hold shift and click to select multiple lecturers', related_name='projects', to='accounts.lecturerprofile'),
        ),
    ]
