# Generated by Django 4.2.15 on 2024-08-25 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_lecturerprofile_user_alter_studentprofile_user'),
        ('project_app', '0002_project_supervisors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comments', to='accounts.lecturerprofile'),
        ),
        migrations.AlterField(
            model_name='grade',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='accounts.lecturerprofile'),
        ),
        migrations.AlterField(
            model_name='project',
            name='student',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.studentprofile'),
        ),
    ]
