# Generated by Django 4.2.15 on 2024-08-26 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_app', '0003_alter_comment_supervisor_alter_grade_supervisor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='document',
            field=models.FileField(upload_to='projects/documents//%y/%m/%d/'),
        ),
    ]
