# Generated by Django 4.2.15 on 2024-08-25 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of  deartment', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='lecturerprofile',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='studentprofile',
            name='faculty',
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the name of  deartment', max_length=50)),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments', to='accounts.faculty')),
            ],
        ),
        migrations.AlterField(
            model_name='lecturerprofile',
            name='department',
            field=models.ForeignKey(help_text='Choose your department', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.ForeignKey(help_text='Choose your department', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.department'),
        ),
    ]
