# Generated by Django 4.2.15 on 2024-08-25 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_managers_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentprofile',
            old_name='year_of_grad',
            new_name='graduation_year',
        ),
    ]
